[package]
name = "katamari-ffi"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[profile.dev]
opt-level = 2
debug = "full"
overflow-checks = false
debug-assertions = false
panic = "abort"

[dependencies]
eyre = "0.6.12"
windows-strings = "0.5.1"

eframe.version = "0.33.3"
eframe.optional = true
winit.version = "0.30.12"
winit.optional = true
winnow.version = "0.7.14"
winnow.optional = true

windows.version = "0.62.2"
windows.features = [
  "Win32_Foundation",
  "Win32_System_LibraryLoader",
  "Win32_System_Memory",
]

[features]
default = ["ui"]
ui = ["dep:eframe", "dep:winit", "dep:winnow"]
