name: Build
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: ilammy/setup-nasm@v1

      - run: rustup target add x86_64-pc-windows-msvc

      - uses: actions/checkout@v6

      - name: Build
        run: cargo build --no-default-features
