name: Build
on: [push]
jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: ilammy/setup-nasm@v1

      - run: rustup override set nightly

      - uses: actions/checkout@v6

      - name: Build
        run: cargo build --no-default-features
